---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubectl
  name: kubectl-pod
spec:
  serviceAccount: jenkins
  containers:
  - name: kubectl
    image: ebisuyak/kubectl:v1.18.2
    command:
    - tail
    - -f
    - /dev/null
