master:
  servicePort: 8080
  serviceType: NodePort
  nodePort: 32123
  scriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
  installPlugins:
    - kubernetes:1.25.7
    - workflow-aggregator:2.6
    - workflow-job:2.33
    - credentials-binding:1.23
    - git:3.11.0

agent:
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock

persistence:
  enabled: true
  storageClass: jenkins-volume
  size: 10Gi

networkPolicy:
  enabled: false
  apiVersion: networking.k8s.io/v1
